import BottomBar from "components/BottomBar";
import EpisodesForYou from "components/EpisodesForYou";
import GoodEveningSection from "components/GoodEveningSection";
import MainLayout from "components/MainLayout";
import Sidebar from "components/Sidebar";
import Topbar from "components/Topbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden">
        <Sidebar />
        <div className="ml-48 md:ml-48 overflow-hidden">
          <Topbar />
          <MainLayout>
            <GoodEveningSection />
            <EpisodesForYou />
            <EpisodesForYou />
            <EpisodesForYou />
            <EpisodesForYou />
            <EpisodesForYou />
            <EpisodesForYou />
          </MainLayout>
          <BottomBar />
        </div>
      </div>
    </>
  );
}
